# Site settings
title: The Way Broadly
header-img: img/home-bg.png
email: dschlaud@gmail.com
copyright_name: dschlauderaff
description: > # this means to ignore newlines until "baseurl:"
  A blog about learning to code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dschlauderaff
learn_profile: dschlauderaff
email_username: dschlaud@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
